class Kernel extends HttpKernel
{
    // ... existing code ...
    protected $middlewareGroups = [
        // ... existing code ...
        'web' => [
            // ... existing code ...
            \App\Http\Middleware\SetLocale::class,
            // ... existing code ...
        ],
        // ... existing code ...
    ];
    // ... existing code ...
}